### ISSUE TITLE
CSS is inconsistent between `05.md` and `box-styles.css`

### ISSUE THREAD

**Issue by yaseenkadir** [kentcdodds/react-fundamentals#136]
Preface by saying, I'm really enjoying the course. Thanks Kent! Find just the most minor inconsistency between the actual markdown instructions and the actual css.

For the 5th exercise, the [markdown instructions](https://github.com/kentcdodds/react-fundamentals/blame/c10d26aedc5e38e5fe3ac02b9667f45b5daf4e6d/src/exercise/05.md#L55-L69) show the following css

```css
.box {
  border: 1px solid #333;
}
.box--large {
  width: 180px;
  height: 180px;
}
.box--medium {
  width: 120px;
  height: 120px;
}
.box--small {
  width: 60px;
  height: 60px;
}
```

But the `box-styles.css` file has https://github.com/kentcdodds/react-fundamentals/blob/2025be8329c8fc59c27ef813416836e8a50fa85c/src/box-styles.css#L1-L19

Where the diff is specifically
```
2a3,6
>   display: flex;
>   flex-direction: column;
>   justify-content: center;
>   text-align: center;
5,6c9,10
<   width: 180px;
<   height: 180px;
---
>   width: 270px;
>   height: 270px;
9,10c13,14
<   width: 120px;
<   height: 120px;
---
>   width: 180px;
>   height: 180px;
13,14c17,18
<   width: 60px;
<   height: 60px;
---
>   width: 90px;
>   height: 90px;
```

From some poking around in the code, I don't believe there are any instructions that suggest we should update the css styles as part of the exercise. But I'm not 100% certain. Do we want the markdown to be consistent with the actual file content? Or is this inconsistency safe to ignore?
